{{$PROMETHEUS_STORAGE_CLASS_PROVISIONER := DefaultParam .PROMETHEUS_STORAGE_CLASS_PROVISIONER "kubernetes.io/gce-pd"}}
{{$PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE := DefaultParam .PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE "pd-ssd"}}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/vsan:5249834a9f288b9b-4e35d9ee48be834d/"
{{if .RetainPD}}
reclaimPolicy: Retain
{{end}}
