{
 "title": "ClusterAPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeslot", "query": "1m,3m,5m,10m" },
   {
    "name": "job",
    "query": "label_values(controller_runtime_reconcile_time_seconds_count, job)"
   }
  ]
 },
 "panels": [
  { "title": "Rest Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request to KubeAPI Rate",
   "type": "graph",
   "description": " rest_client_requests_total Number of HTTP requests, partitioned by status code, method, and host.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (host, code) (rate(rest_client_requests_total{job=~\"$job\"}[$timeslot]))",
     "legendFormat": "{{host}}-{{code}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"GET\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Get Request Latency 90%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"GET\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Post Request Latency 99%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"POST\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Post Request Latency 90%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"POST\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Patch Request Latency 99%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"PATCH\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Patch Request Latency 90%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"PATCH\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Delete Request Latency 99%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"DELETE\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  {
   "title": "Delete Request Latency 99%",
   "type": "graph",
   "description": "rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"$job\", verb=\"DELETE\"}[$timeslot])) by (job, le))"
    }
   ]
  },
  { "title": "Process Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Resident Memory",
   "type": "graph",
   "description": " Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "description": " Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " process_virtual_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "process_cpu_seconds_total Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "graph",
   "description": "process_open_fds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}"
    }
   ]
  },
  { "title": "Go Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Go routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\"}"
    }
   ]
  },
  { "title": "Controller Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Reconcile Time",
   "type": "graph",
   "description": "controller_runtime_reconcile_time_seconds Length of time per reconciliation per controller",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Rate",
   "type": "graph",
   "description": " controller_runtime_reconcile_total Total number of reconciliations per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{job=~\"cap(i|v).*\"}[5m])",
     "legendFormat": "{{controller}}-{{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Error Rate",
   "type": "graph",
   "description": " controller_runtime_reconcile_errors_total Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{job=~\"cap(i|v).*\"}[5m])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "graph",
   "description": "controller_runtime_active_workers Number of currently used workers per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=~\"cap(i|v).*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Max Concurrent Reconciles Number",
   "type": "graph",
   "description": "controller_runtime_max_concurrent_reconciles Maximum number of concurrent reconciles per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles{job=~\"cap(i|v).*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "WorkQueue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Workqueue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{job=~\"cap(i|v).*\"}"
    }
   ]
  },
  {
   "title": "Workqueue Longest Item Running Time",
   "type": "graph",
   "description": "workqueue_longest_running_processor_seconds How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{job=~\"cap(i|v).*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Unfinished Item Running Time",
   "type": "graph",
   "description": "workqueue_unfinished_work_seconds How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{job=~\"cap(i|v).*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Add Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{job=~\"cap(i|v).*\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Retries Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{job=~\"cap(i|v).*\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration for 100%",
   "type": "graph",
   "description": "workqueue_queue_duration_seconds How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.00, rate(workqueue_queue_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration for 99%",
   "type": "graph",
   "description": "workqueue_queue_duration_seconds How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(workqueue_queue_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration for 90%",
   "type": "graph",
   "description": "workqueue_queue_duration_seconds How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(workqueue_queue_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration for 50%",
   "type": "graph",
   "description": "workqueue_queue_duration_seconds How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(workqueue_queue_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Work Duration for 100%",
   "type": "graph",
   "description": " workqueue_work_duration_seconds How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.00, rate(workqueue_work_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Work Duration for 99%",
   "type": "graph",
   "description": " workqueue_work_duration_seconds How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(workqueue_work_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Work Duration for 90%",
   "type": "graph",
   "description": " workqueue_work_duration_seconds How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(workqueue_work_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Work Duration for 50%",
   "type": "graph",
   "description": " workqueue_work_duration_seconds How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(workqueue_work_duration_seconds_bucket{job=~\"cap(i|v).*\"}[5m]))",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  }
 ]
}