{
 "title": "Cluster-Host-Resource-Usage-Node-Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeslot", "query": "1m,3m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "CPU  Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$timeslot])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Total Cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory-Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Cached_bytes{} - node_memory_Buffers_bytes{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory-Total/Free/Cache/Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "FREE-{{instance}}" },
    { "expr": "node_memory_Cached_bytes{}", "legendFormat": "CACHE-{{instance}}" },
    {
     "expr": "node_memory_Buffers_bytes_bytes{}",
     "legendFormat": "BUFFER-{{instance}}"
    },
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "TOAL-{{instance}}" }
   ]
  },
  {
   "title": "Storage-Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sda1\"} - node_filesystem_avail_bytes{device=\"/dev/sda1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage-Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sda1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[$timeslot])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Network Transit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[$timeslot])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  }
 ]
}