{
 "title": "Pod/Container-Resource-Usage-CAdvisor",
 "time": { "from": "2021-11-11T09:08:16.000Z", "to": "2021-11-11T10:30:19.000Z" },
 "templating": {
  "list": [
   { "name": "timeslot", "query": "1m,3m,5m,10m" },
   { "name": "pod", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage by POD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", pod=~\"$pod\"}[$timeslot])) by (pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", pod=~\"$pod\"}[$timeslot])) by (container, pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "CPU throttle Percentage by Container",
   "type": "graph",
   "description": " throttled percentage := container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container!=\"\", pod=~\"$pod\"}[$timeslot])/rate(container_cpu_cfs_periods_total{container!=\"\", pod=~\"$pod\"}[$timeslot])",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "CPU throttle by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{container!=\"\", pod=~\"$pod\"}[$timeslot])) by (pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", pod=~\"$pod\"}) by (pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", pod=~\"$pod\"}) by (container, pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory WorkingSet by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod=~\"$pod\"}) by (pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory WorkingSet by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod=~\"$pod\"}) by (container, pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory RSS by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\", pod=~\"$pod\"}) by (container, pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory RSS by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\", pod=~\"$pod\"}) by (container, pod, instance)",
     "legendFormat": "{{instance}}-{{pod}}-{{container}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "FS Write Bytes by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(container_fs_writes_bytes_total{container!=\"\",pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "FS Read Bytes by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(container_fs_reads_bytes_total{container!=\"\",pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Network Receive Bytes by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(container_network_receive_bytes_total{id!=\"/\", pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bytes by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(container_network_transmit_bytes_total{id!=\"/\"}[1m]))",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Receive Avg Packet Size by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(container_network_receive_bytes_total{id!=\"/\", pod=~\"$pod\"}[$timeslot])) / sum by (pod, instance) (rate(container_network_receive_packets_total{id!=\"/\", pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transit Avg Packet Size by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(container_network_transmit_bytes_total{id!=\"/\", pod=~\"$pod\"}[$timeslot])) / sum by (pod, instance) (rate(container_network_transmit_packets_total{id!=\"/\", pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Received/Transmit Packet Drop by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, pod) (rate(container_network_receive_packets_dropped_total{pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}-received"
    },
    {
     "expr": "sum by (instance, pod) (rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "Network Received/Transmit Errors by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, pod) (rate(container_network_receive_errors_total{pod=~\"$pod\"}[$timeslot]))",
     "legendFormat": "{{instance}}-{{pod}}-received"
    }
   ]
  }
 ]
}