apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    size: {{.SVCSizeLabel}}
spec:
  type: ClusterIP
  selector:
    name: {{.DeploymentBaseName}}-{{.Index}}
  ports:
  - port: 8080
    targetPort: 80
