{{$PROMETHEUS_SCRAPE_ETCD := DefaultParam .PROMETHEUS_SCRAPE_ETCD false}}
{{$PROMETHEUS_SCRAPE_NODE_EXPORTER := DefaultParam .PROMETHEUS_SCRAPE_NODE_EXPORTER false}}

# If kube-apiserver is overloaded, we might get slower responses.
{{$PROMETHEUS_SLOW_APISERVER := DefaultParam .CL2_PROMETHEUS_SLOW_APISERVER false}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: master
  name: master
  namespace: monitoring
spec:
  endpoints:
  {{if $PROMETHEUS_SCRAPE_ETCD}}
  - interval: 5s
    port: etcd-2379
    scheme: https                                                               
    tlsConfig:                                                                  
      certFile: /etc/prometheus/secrets/kube-etcd-client-certs/server.crt          
      insecureSkipVerify: true                                                  
      keyFile: /etc/prometheus/secrets/kube-etcd-client-certs/server.key
  # - interval: 5s
  #   port: etcd-2382
  {{end}}
  {{if $PROMETHEUS_SCRAPE_NODE_EXPORTER}}
  # TODO(mborsz): Debug why node-exporter is that slow and change interval back to 5s.
  - interval: 30s
    port: node-exporter
    scrapeTimeout: 20s
  {{end}}
  - port: apiserver
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    {{if $PROMETHEUS_SLOW_APISERVER}}
    interval: 30s
    scrapeTimeout: 30s
    {{else}}
    interval: 5s
    {{end}}
  - interval: 5s
    port: kubelet
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kubelet
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics/cadvisor
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kube-scheduler
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kube-controller-manager
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    k8s-app: master
